### ISSUE TITLE
question about the  parameters of 'flip' operation in run_example.py

### ISSUE THREAD

**Issue by Andantino97** [MichiganCOG/TASED-Net#10]
Hi,
I'm quite interested in your excellent work and I've replicated that with your clear-meaning code. 
And  now I have a question about [this line](https://github.com/MichiganCOG/TASED-Net/blob/master/run_example.py/#L78)

Theoretically, maybe you mean this operation is to get a reverse order of the clips if the frame is in the first 32 frames.i.e. original order is {f1, f2, ... , f32} and after the flip operation it changes to {f32, f32, ..., f1}, however, the shape of **clip** is **[1, 3, 32, 224, 384]** and in your code, you performed a flip operation in the second dimension(**torch.flip(clip, [1])**), which means that to flip the RGB channel and get a reverse order, maybe I think it is supposed to be **torch.flip(clip, [2])** to get a flip operation in the third dimension? Namely to operate on **32**, not **3**.

Am I right?
Looking forward to your reply, thank you!

**Comment by kylemin** [comment]
Hi,
You are totally right! Thank you for pointing it out. It should be torch.flip(clip, [2]).
I will edit the line right away.
Thank you again.
Kyle

**Comment by Andantino97** [comment]
Hi Kyle,
It's my pleasure to do that.
And thank you for your reply, now I have a clearer understanding of the code!

Best regards.
Hao
