### ISSUE TITLE
How did you updated your model?

### ISSUE THREAD

**Issue by titi-97** [MichiganCOG/TASED-Net#12]
Hi,
We want to know something about the **updated** TASED Net.
Did you use different training tricks or modify the structure of the reported model to get a better performance?
Could you please give some details about the difference between the two versions?
Thank you!

**Comment by kylemin** [comment]
Hi,
Thank you for your interest.
We used a different temporal aggregation strategy (please refer to Figure 4 of our paper) by slightly modifying the model structure.
Specifically, we changed [self.convtsp4](https://github.com/MichiganCOG/TASED-Net/blob/b100fa76c73f0fe830e632a38c0b55353206c1ff/model.py#L58) in the `model.py`.
We did not use any training tricks.
Thank you.
Kyle

**Comment by titi-97** [comment]
Hi, Kyle
Thanks for your reply. That helps me a lot.
Hope you have more great achievements in this area! 

Best regards,
Titi.
