### ISSUE TITLE
Evaluation Code

### ISSUE THREAD

**Issue by silent357** [MichiganCOG/TASED-Net#13]
Thank you for your excellent work. I produce saliency maps by your released model but find evaluation results are different from the reported values. I used the code provided by https://github.com/wenguanwang/DHF1K/blob/master/code_for_Metrics.zip. Could you please more details on evaluation? Thank you!

**Comment by kylemin** [comment]
Hi,
Thank you for your interest.
We double-checked the performance by submitting the results to DHF1K benchmark team, so I believe the produced saliency maps should be accurate.
I am wondering how different were the results?

**Comment by silent357** [comment]
Thank you for your prompt reply! Since I did not submit results to DHF1K benchmark team, I only evaluate the model on the validation set of DHF1K. I found the values are a little higher than the reported results in your paper. So I just want to make sure whether you used https://github.com/wenguanwang/DHF1K/blob/master/code_for_Metrics.zip for evaluation.

**Comment by kylemin** [comment]
As we mentioned in the README, the released TASED-Net is a modified one to improve the performance, so the values should be higher than the reported ones.
We referred to the following two repositories for evaluation.
[Python](https://github.com/tarunsharma1/saliency_metrics/blob/master/salience_metrics.py)
[MATLAB](https://github.com/wenguanwang/DHF1K/blob/master/code_for_Metrics.zip)
Thank you.

**Comment by silent357** [comment]
Thank you very much.

**Comment by peterwilson3912** [comment]
> As we mentioned in the README, the released TASED-Net is a modified one to improve the performance, so the values should be higher than the reported ones.
> We referred to the following two repositories for evaluation.
> [Python](https://github.com/tarunsharma1/saliency_metrics/blob/master/salience_metrics.py)
> [MATLAB](https://github.com/wenguanwang/DHF1K/blob/master/code_for_Metrics.zip)
> Thank you.

Thank you so much for your amazing project! Would it be possible to release your code for evaluation? That would be super helpful!

**Comment by kylemin** [comment]
@karliell Sorry for the late response. Here is our code for evaluation: [link](https://drive.google.com/file/d/1u6Y1CtYXWj4ruQrhR-jSOCe86LwnV_9G/view?usp=sharing)
