### ISSUE TITLE
Some question about the model

### ISSUE THREAD

**Issue by GewelsJI** [MichiganCOG/TASED-Net#14]
Hello, Kyle!

I am a researcher from Wuhan University. Recently, I am paying attention to the paper appeared in 2019'ICCV, i.e., TASED-Net: Temporally-Aggregating Spatial Encoder-Decoder Network for Video Saliency Detection.

When I read the code and paper you provided in the GitHub, I find the module (Max-pool 2x2x2 Stride 2, 2, 2) appeared in the figure.2 (top-right), but it does not appear in the code [line89-line91](https://github.com/MichiganCOG/TASED-Net/blob/b100fa76c73f0fe830e632a38c0b55353206c1ff/model.py#L90). So what's the difference between two versions?

I am looking forward to your quick reply.

Best regards,
Ge-Peng.

**Comment by kylemin** [comment]
Dear Ge-Peng,

Thank you for your interest.
We did not apply 2x2x2 max-pooling because this operation is redundant.
Applying 2x2x2 max-pooling is equivalent to applying 2x1x1 and 1x2x2 max-poolings sequentially, which are already implemented by auxiliary poolings (line 90-91 of `model.py`).
Thank you.

**Comment by GewelsJI** [comment]
Yeah, I understand it. Thus, this part of code is mis-match the origin paper (ie, a pipeline in the figure. 2) due to you adopt the more efficient alternative plan.

By the way, why not try 3x1x1 and 1x3x3 max-poolings sequentially to replace the sub-operation (Max-pool 2x2x2 Stride 3, 3, 3)?

Thank you again for your kindness reply.

Best,
Ge-Peng

**Comment by kylemin** [comment]
That is correct. You can think of our code as an optimized implementation of Figure 2.

Did you mean the 3x3x3 max-pooling with stride (2,2,2)?
I think you can change the first auxiliary pooling from 4x1x1 to 3x1x1 max-pooling if you want a more efficient implementation. However, this modification will require changing the architecture of the prediction network. You can try!

Thank you.
Kyle

**Comment by GewelsJI** [comment]
Yeah, I will try it. 

Thank you again.
Ge-Peng.
