### ISSUE TITLE
What's this repo's dependency and requirements?

### ISSUE THREAD

**Issue by wbzhang233** [MichiganCOG/TASED-Net#17]
I want to know the python environment dependency and all package's version.

**Comment by kylemin** [comment]
Hi,
Thank you for your interest.
This repository uses the following modules or libraries: os, sys, csv, time, datetime, itertools, cv2, numpy, scipy, and torch.
I believe it is only the PyTorch version that matters.
We originally used PyTorch 0.4.0 (python 3.6.5) during the development stage, but the released code was tested with PyTorch 1.3.1 (python 3.6.7).

**Comment by Jiexin-Zheng** [comment]
hi, excuse me, I want to now how to get the qualitative results of the images(does that kind of map have a name?)? I run your code and I could only get the saliency map
