### ISSUE TITLE
May I ask whether the results you list on your website is on DHF1K validation dataset?

### ISSUE THREAD

**Issue by peterwilson3912** [MichiganCOG/TASED-Net#21]
Thank you so much for your reply! The work is amazing. 
You mention that you don't have information about the test set. 
May I ask whether the results you list on your website are on the DHF1K validation dataset?

![image](https://user-images.githubusercontent.com/36145675/125877137-6e5f2b0c-eb18-4201-97ec-402d5f95bb7e.png)

The figure makes me confused is this one:
![image](https://user-images.githubusercontent.com/36145675/125877221-be06d342-f9c9-4e36-9dda-2757a2824b24.png)

You say "testset". These numbers are also those list on board. I want to double-check which dataset gets those numbers.

Thanks!

**Comment by kylemin** [comment]
It is on the test set!
Now I see what you meant. You can submit your prediction maps to the DHF1K team. They will give you the scores.
Please refer to the README of this [DHF1K repository](https://github.com/wenguanwang/DHF1K). It has a detailed instruction.

**Comment by peterwilson3912** [comment]
Ohhhh Good to know! It's confusing at the beginning. haha, I was wondering why people get that score. Thanks a lot!
