### ISSUE TITLE
Testing says ' more frames are needed'

### ISSUE THREAD

**Issue by arsalasif** [MichiganCOG/TASED-Net#3]
Hi,

I'm trying to test on sequences from UCF-Sports, Hollywood-2 and DHF1K datasets.

For UCF sequences, it keeps saying more frames are needed. Please advise.

**Comment by kylemin** [comment]
Hi,

For short videos with fewer than 63 frames, we repeated those videos multiple times.
For example, let's say that we have a video having 40 frames: v={f1, f2, f3, ..., f40}.
Then, we build our input as i={f1, f2, f3, ..., f40, f1, f2, f3, ..., f23}.
The output will look like o={s1, s2, ... s63}, so you can take the first 40 maps, which is o'={s1, s2, ..., s40}. (For smoother input, you can also try v''={f1, f2, f3, ..., f40, f39, f38, f37, ..., f17}. I think it can depend on you.)

I hope it helps.

**Comment by arsalasif** [comment]
Thanks for clearing that up! Much appreciated.

**Comment by Andantino97** [comment]
Dear Kyle,

Could you please share the test code for the datasets which have less than 63 frames (like UCF and Hollywood)?

I think that I have problems when I'm evaluating the samples which have less than 63 frames. I write the repeat code by myself but the results are much different from the ground truth. I think there may be something wrong with my code. And also I realized that when evaluating, the metrics compare the results and ground truth frame by frame, which means, the order of results should match the ground-truth exactly. I think when generating results with my repeat code, there is something wrong with the order. So I hope that there could be something I can refer to.

P.S. Your code performs correctly on the samples with more than 63 frames. There isn't anything wrong with that :)

Looking forward to your reply.
Thank you!

Best regards,
Hao.
