### ISSUE TITLE
There are some problems with reading the data。

### ISSUE THREAD

**Issue by YanDingXin** [MichiganCOG/TASED-Net#4]
Hello, I am very interested in your work. However, I have some questions when I try to execute your code. Could you please answer me?
Why do you perform this (img = img[...,::-1]) to reverse all data when the test code you gave reads the data?Why do you do that?Is it because you did it in training, so you need to do it in testing?
Hope you can reply as soon as possible, thank you very much!
the code in mian:

For I in range (len (list_frames)) :
Img = cv2.imread(os.path.join(path_indata, dname, list_frames[I]))
Img = cv2.resize(img, (384, 224))
Img = img [..., : : 1]
The snippet. Append (img)

**Comment by GewelsJI** [comment]
Hi, Can you explain it clearly?

**Comment by YanDingXin** [comment]
Opencv reads images in BGR format, so the channel is transformed to RGB format in this way.

**Comment by YanDingXin** [comment]
> Hi, Can you explain it clearly?
Opencv reads images in BGR format, so the channel is transformed to RGB format in this way.

**Comment by GewelsJI** [comment]
Tks for your reply, happy time

**Comment by GewelsJI** [comment]
@YanDingXin Another question is this [line](https://github.com/MichiganCOG/TASED-Net/blob/e1c2d15a98e93a1520c7802fd04b42a6df4de7eb/dataset.py#L38), can you explain it? thank you again!

**Comment by YanDingXin** [comment]
> @YanDingXin Another question is this line, can you explain it? thank you again!

I didn't find the role of  v  in their paper, perhaps I was careless.However, we can clearly guess that it should be a threshold to decide whether to perform symmetric operation on the image(img[:, ::-1, ...] and annt[:, ::-1]), i.e. data enhancement.

**Comment by kylemin** [comment]
@YanDingXin Thank you for your contribution. Yes, it is for data augmentation (horizontal flipping). It is a common technique.
