### ISSUE TITLE
Some problem when i training on my custom dataset

### ISSUE THREAD

**Issue by GewelsJI** [MichiganCOG/TASED-Net#6]
The first issue is how can you deal with the "problem" in your paper:

> The problem with this configuration is that the first $T-1$ saliency maps are not predicted.

In your `dataset.py` python file, I fail to find anything process this question.

And the second issue is what's function of this [line](https://github.com/MichiganCOG/TASED-Net/blob/e1c2d15a98e93a1520c7802fd04b42a6df4de7eb/dataset.py#L39)

Thank you for your kind reply!

Best wishes!

Gepeng-Ji

**Comment by kylemin** [comment]
Dear Gepeng-Ji,

For the first question, the answer is in [here](https://github.com/MichiganCOG/TASED-Net/issues/3#issuecomment-542496309) and [here](https://github.com/MichiganCOG/TASED-Net/blob/e1c2d15a98e93a1520c7802fd04b42a6df4de7eb/run_example.py#L76) (Our testing scheme predicts only the last frame of each input clip, so the first 31 frames are not processed. As a workaround to process those frames, I flipped the first 31 segments).

For the second question, it is for data augmentation (horizontal flipping). It is a common technique.

Thank you for your interest.

**Comment by GewelsJI** [comment]
Dear Kylemin, 

Firstly, thank for your quick reply.

In your explaination, you just process this problem in your testing code and you discard the first T frames in your training process? Is that right?

Thank you again!

**Comment by kylemin** [comment]
No, that is not what I wrote about. Our testing scheme does not discard the frames. As I mentioned earlier, we flip the first T-1 segments to process the first T-1 frames. By doing so, we can process all the frames of a video. Please check lines 76-78 of run_example.py.

Thank you.

**Comment by GewelsJI** [comment]
Yeap, what i mean is training process. Not testing process.

**Comment by kylemin** [comment]
Oh yes, we did not consider the first T-1 frames in training.

Thank you.

**Comment by GewelsJI** [comment]
Thank you for your kindness reply.

And Do you make some effort for salient object detection in object-level instead of eye-fixation prediction?

**Comment by kylemin** [comment]
No, we have not applied this work to other areas yet.

**Comment by GewelsJI** [comment]
Thanks and happy time! :)
